name = plutoniumships
title = Plutonium's Ships
author = plutonium
description = Turn your constructions into boats or blimps and set off on the adventure aboard the ship of your dreams. 
version = 1
depends = default, wool, xdecor
